locals {
  subscription_resource_id = startswith(var.subscription_id, "/subscriptions/") ? var.subscription_id : "/subscriptions/${var.subscription_id}"

  allowed_resource_types = [
    "Microsoft.Resources/subscriptions/resourceGroups",
    "Microsoft.Authorization/policyAssignments",
    "Microsoft.Authorization/policyDefinitions",
    "Microsoft.Authorization/policySetDefinitions",
    "Microsoft.Authorization/roleAssignments",
    "Microsoft.Authorization/locks",
    "Microsoft.Consumption/budgets",
    "Microsoft.Resources/deployments",
    "Microsoft.Network/virtualNetworks",
    "Microsoft.Network/virtualNetworks/subnets",
    "Microsoft.Network/virtualNetworks/virtualNetworkPeerings",
    "Microsoft.Network/networkSecurityGroups",
    "Microsoft.Network/networkSecurityGroups/securityRules",
    "Microsoft.Network/publicIPAddresses",
    "Microsoft.Network/networkInterfaces",
    "Microsoft.Network/routeTables",
    "Microsoft.Network/routeTables/routes",
    "Microsoft.Network/bastionHosts",
    "Microsoft.Network/privateEndpoints",
    "Microsoft.Network/privateEndpoints/privateDnsZoneGroups",
    "Microsoft.Network/privateDnsZones",
    "Microsoft.Network/privateDnsZones/virtualNetworkLinks",
    "Microsoft.Network/networkWatchers",
    "Microsoft.Network/networkWatchers/flowLogs",
    "Microsoft.Compute/virtualMachines",
    "Microsoft.Compute/disks",
    "Microsoft.Compute/virtualMachineScaleSets",
    "Microsoft.ManagedIdentity/userAssignedIdentities",
    "Microsoft.Storage/storageAccounts",
    "Microsoft.Storage/storageAccounts/blobServices",
    "Microsoft.Storage/storageAccounts/blobServices/containers",
    "Microsoft.KeyVault/vaults",
    "Microsoft.OperationalInsights/workspaces",
    "Microsoft.OperationalInsights/workspaces/tables",
    "Microsoft.Insights/diagnosticSettings",
    "Microsoft.Insights/metricAlerts",
    "Microsoft.Insights/actionGroups",
    "Microsoft.Insights/scheduledQueryRules"
  ]
}
